services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - mariadb-default

networks:
  mariadb-default:
    external: true